### ISSUE TITLE
AdminMenu

### ISSUE THREAD

**Issue by FransFX** [AmirrezaJaberi/FIREAC#100]
Admin Menu Does Not Come Up When Key Is Pressed? No Errors On Consols
![Screenshot 2024-02-26 125314](https://github.com/AmirrezaJaberi/FIREAC/assets/106434295/fc568441-b268-4626-8d44-3a0c422eaf34)
Showing this error aswell?

**Comment by FransFX** [comment]
Slaap julle?>

**Comment by FransFX** [comment]
The commands does nothing

**Comment by djoo1** [comment]
in the new vesion they change many things so the admin menu not working anymore ;
so i just installed the older version (december version) and everything good now
