### ISSUE TITLE
Getting kicked and erorr

### ISSUE THREAD

**Issue by harshit2121** [AmirrezaJaberi/FIREAC#102]
Im getting notfiy in discord webhook and also getting error logs continues idk why?
also how to whilistlist an admin need help inthat?
![image](https://github.com/AmirrezaJaberi/FIREAC/assets/135013888/9cbe117d-e551-4787-98bd-7ef943d9a8eb)
![image](https://github.com/AmirrezaJaberi/FIREAC/assets/135013888/9fa19268-686f-455e-8a17-63bafcc7d8e0)

**Comment by djoo1** [comment]
all of this happend to me so i just installed the older version and now everythinf ok , and for the admins i add them directly in the database
