### ISSUE TITLE
Failure on FIREAC Live Console, and F8 Console

### ISSUE THREAD

**Issue by bylickilabs** [AmirrezaJaberi/FIREAC#103]
HI, I downloaded your antiCheat today and installed it on my server! Unfortunately there are numerous messages in the consoles.

![4](https://github.com/AmirrezaJaberi/FIREAC/assets/109308073/37436d43-23af-4ee3-8970-bdcf9cca5a45)
![5](https://github.com/AmirrezaJaberi/FIREAC/assets/109308073/7efa81cf-9685-4b47-833f-bb29ba7bcf2f)

**Comment by djoo1** [comment]
that happend to me so i just installed version 7.0 (december version) and everything is good now
