### ISSUE TITLE
Alot of issues

### ISSUE THREAD

**Issue by devgodstudio** [AmirrezaJaberi/FIREAC#105]
It seems like there is a few typos and some other issues, 
I was looking forward to using this as a test before purchasing but unfortunately I cannot use it in the current state,
I have managed to change a few things and get it sorta working but every time I fix one thing I find another issue so.

Thanks, 
please fix the script.

**Comment by AmirrezaJaberi** [comment]
Hi , our anti-cheat fixed in 7.1.1 version

Thanks for your reprot
