### ISSUE TITLE
dosent ban people 

### ISSUE THREAD

**Issue by johnkouk007** [AmirrezaJaberi/FIREAC#109]
[  script:FIREAC-main] FIREAC: Player johnkouk007 Banned From Server | Reason:  Anti Teleport
[  script:FIREAC-main] SCRIPT ERROR: @FIREAC-main/src/fire-server.lua:2011: attempt to index a nil value (local 'Emoji')
[  script:FIREAC-main] > FIREAC_MESSAGE (@FIREAC-main/src/fire-server.lua:2011)
[  script:FIREAC-main] > FIREAC_ACTION (@FIREAC-main/src/fire-server.lua:1941)
[  script:FIREAC-main] > handler (@FIREAC-main/src/fire-server.lua:38)
[  script:FIREAC-main] > rawQuery (@oxmysql/dist/build.js:26467)
[  script:FIREAC-main] > processTicksAndRejections (node:internal/process/task_queues:96)

that is the only thing i get but it dosnt kick me or ban me...

**Comment by johnkouk007** [comment]
function FIREAC_ACTION (FIREAC.ScreenShot.Log is nil)

**Comment by johnkouk007** [comment]
[ script:esx_property] [INFO] Added Property into datastore_data table
[       script:FIREAC] FIREAC: Player johnkouk007 Connecting ...
[      script:hardcap] Connecting: johnkouk007
[       script:FIREAC] SCRIPT ERROR: @FIREAC/src/fire-server.lua:2888: attempt to index a nil value (field '?')
[       script:FIREAC] > fn (@FIREAC/src/fire-server.lua:2888)
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[       script:FIREAC] SCRIPT ERROR: Execution of native 0000000054c06897 in script host failed: Argument at index 0 was null.
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:1293)

**Comment by sleepingezy** [comment]
I agree, it only bans 1 person since after that it detects all bans as ID 1. then oxmysql will state that there is duplicate entry for ID 1 then will no longer ban the person.
![image_2024-07-02_070204925](https://github.com/AmirrezaJaberi/FIREAC/assets/98477961/8fdcab5c-a076-45bc-90a6-1e55f81ec6d2)

**Comment by AmirrezaJaberi** [comment]
This bug fixed in new version
