### ISSUE TITLE
: Execution of native 0000000054c06897 in script host failed: Argument at index 0 was null.

### ISSUE THREAD

**Issue by DustDevelopment** [AmirrezaJaberi/FIREAC#112]
[       script:FIREAC] SCRIPT ERROR: Execution of native 0000000054c06897 in script host failed: Argument at index 0 was null.
[       script:FIREAC] > GetPlayerToken (GetPlayerToken.lua:6)
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:1293)
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.

**Comment by RDMMDLC** [comment]
any solution????

**Comment by AmirrezaJaberi** [comment]
This bug fixed in new version
