### ISSUE TITLE
It only bans 1 player. then the other players who are using blacklist arent

### ISSUE THREAD

**Issue by sleepingezy** [AmirrezaJaberi/FIREAC#114]
After FIREAC detects 1 player. SQL only saves 1 ID banned player. Then the following players who are detected as "banned" can re enter the server since SQL only saves 1 and considers the rest as duplicate then it won't save the rest.

![image_2024-07-02_071041600](https://github.com/AmirrezaJaberi/FIREAC/assets/98477961/42a1b08e-f4a9-4386-81b3-768771f15d7d)

**Comment by AmirrezaJaberi** [comment]
This bug fixed in new version
