### ISSUE TITLE
Admin menu not does not respond

### ISSUE THREAD

**Issue by tibike2009** [AmirrezaJaberi/FIREAC#115]
Well, my problem would be that the admin menu opens, which is great, the only problem is that it doesn't respond to anything
![image222](https://github.com/AmirrezaJaberi/FIREAC/assets/130681632/e0b02650-c134-4c82-852d-b3bf5a2a21db)

**Comment by jakemm1** [comment]
any solution me to

**Comment by AmirrezaJaberi** [comment]
This bug fixed in new version
