### ISSUE TITLE
SCRIPT ERROR: @FIREAC/server/server.lua:1829: attempt to concatenate a nil value (upvalue 'COUNTRY')

### ISSUE THREAD

**Issue by KostaZx** [AmirrezaJaberi/FIREAC#59]
SCRIPT ERROR: @FIREAC/server/server.lua:1829: attempt to concatenate a nil value (upvalue 'COUNTRY')

**Comment by AmirrezaJaberi** [comment]
Hi @KostaZx  , this is your web API connection problem
Please check your internet connection and firewall (anti virus or anti DDoS)
