### ISSUE TITLE
Support for txadmin?

### ISSUE THREAD

**Issue by mwuhahaa** [AmirrezaJaberi/FIREAC#65]
Is it possible for you to add support for txadmin so admins wont get banned when they use noclip or any other mod from that menu ?

**Comment by AmirrezaJaberi** [comment]
> and maybe if you could add something in the lines of checking player inventory and cash/bank balance so i could use only this menu for administratrion.

Hi @mwuhahaa,

I never use any base for FIREAC
for example ESX or QBCORE because I need every one use that
but you can change our code for your self
