### ISSUE TITLE
Anti Resource Stopper not working

### ISSUE THREAD

**Issue by StomperG** [AmirrezaJaberi/FIREAC#66]
You are able to stop the anticheat on loading screen, if you do that you dont get banned for anything.

**Comment by AmirrezaJaberi** [comment]
Hi, @StomperG 
I will check that

**Comment by Turkisec** [comment]
i can confirm it cheaters can stop FIREAC on joining server

**Comment by iSentrie** [comment]
> Hi, @StomperG I will check that

so was it fixed or what?
