### ISSUE TITLE
Banned for teleporting

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [AmirrezaJaberi/FIREAC#74]
Every new player is getting banned for teleporting when they join my server.
I had to turn off FIREAC in order to make my server playable.
Why is this happening?

**Comment by Player-107** [comment]
You can just disable it in config or change it from BAN to WARN so it doesn’t ban the players

**Comment by PCL-CrisKolkman** [comment]
> You can just disable it in config or change it from BAN to WARN so it doesn’t ban the players

Yeah and completely destroy the purpose of having anti-cheat...

I don't consider this an answer.

**Comment by iSentrie** [comment]
> > You can just disable it in config or change it from BAN to WARN so it doesn’t ban the players
> 
> Yeah and completely destroy the purpose of having anti-cheat...
> 
> I don't consider this an answer.

weirdo

**Comment by AmirrezaJaberi** [comment]
Hi @PCL-CrisKolkman,
Add your player to whitelist for 3 or 4 second in whitelists by our export option after that remove them .

**Comment by PCL-CrisKolkman** [comment]
> Hi @PCL-CrisKolkman, Add your player to whitelist for 3 or 4 second in whitelists by our export option after that remove them .

Yeah this would mean I have to whitelist everyone, because everyone is getting banned for "teleporting".

**Comment by AmirrezaJaberi** [comment]
> > Hi @PCL-CrisKolkman, Add your player to whitelist for 3 or 4 second in whitelists by our export option after that remove them .
> 
> Yeah this would mean I have to whitelist everyone, because everyone is getting banned for "teleporting".

I know what you mean
You mean when player on spawn
Will get ban in spawn

For fix that try add player to whitelist in spawn & after spawn remove them from whitelist
