### ISSUE TITLE
banned adaptive card

### ISSUE THREAD

**Issue by JustAuramo** [AmirrezaJaberi/FIREAC#76]
hey can you make anticheat adaptive card, ban check, and if you are banned you see cards like wx_anticheat

**Comment by AmirrezaJaberi** [comment]
Hi @JustAuramo,
Send photo of that I will check it

**Comment by JustAuramo** [comment]
@AmirrezaJaberi I wish you would make this anticheat have an adaptive card feature like fiveguard has. So if you get banned it says fine that you got banned and it looks fine when you try to connect to the server. The Fiveguard adaptive card feature is awesome and cool. I'd appreciate it if you made one. I'll post some pictures in this thread

**Comment by JustAuramo** [comment]
> Hi @JustAuramo,
> 
> Send photo of that I will check it

![image](https://github.com/AmirrezaJaberi/FIREAC/assets/108193124/b1dfbd7b-1983-4b5b-bfa5-df92213e7579)![image](https://github.com/AmirrezaJaberi/FIREAC/assets/108193124/bbe96e08-3ebc-40f6-82ea-6e59d68ee17b)

**Comment by AmirrezaJaberi** [comment]
![image](https://github.com/AmirrezaJaberi/FIREAC/assets/83431690/81526362-296a-43bc-abd9-c62c53a8f990)
done
