### ISSUE TITLE
function FIREAC_ACTION (FIREAC.ScreenShot.Log is nil)

### ISSUE THREAD

**Issue by novahaxor** [AmirrezaJaberi/FIREAC#90]
console:

[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[       script:FIREAC] SCRIPT ERROR: Execution of native 0000000054c06897 in script host failed: Argument at index 0 was null.
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:1293)

discord:
function StartAntiCheat (Server Port is wrong or We can't connect to that)

**Comment by ByQuadiix** [comment]
Replace line 1292-1293 with this:
local TYPE = GetEntityType(ENTITY)
local OWNER = NetworkGetFirstEntityOwner(ENTITY)
local POPULATION = GetEntityPopulationType(ENTITY)
local MODEL = GetEntityModel(ENTITY)
local HWID = GetPlayerToken(OWNER, 0)

    GetEntityPopulationType(ENTITY)
GetEntityModel(ENTITY) 
    GetPlayerToken(OWNER, 0

**Comment by ByQuadiix** [comment]
And you have to specify the port of your Server in the config

**Comment by novahaxor** [comment]
> Replace line 1292-1293 with this: local TYPE = GetEntityType(ENTITY) local OWNER = NetworkGetFirstEntityOwner(ENTITY) local POPULATION = GetEntityPopulationType(ENTITY) local MODEL = GetEntityModel(ENTITY) local HWID = GetPlayerToken(OWNER, 0)
> 
> GetEntityPopulationType(ENTITY) GetEntityModel(ENTITY) GetPlayerToken(OWNER, 0

definitely helped but now the discord webhooks dont work at all, no errors or anything, installed the same way as before

**Comment by ErrorRExorY** [comment]
Using version 7.1.0 still having this issue..

**Comment by ErrorRExorY** [comment]
Anyone know why? I need those screenshots ^^

I tried it like this:

        local OWNER = NetworkGetFirstEntityOwner(ENTITY)
        local TYPE, POPULATION, MODEL, HWID = GetEntityType(ENTITY), GetEntityPopulationType(ENTITY),
            GetEntityModel(ENTITY), GetPlayerToken(OWNER, 0)
            
            
            And like suggested above
            
            but i always get
            Error: function FIREAC_ACTION (FIREAC.ScreenShot.Log is nil)
License: YOUR SERVER NAME


Port is set

**Comment by ErrorRExorY** [comment]
So, does nobody has any conclusion? Is it because of my Ubuntu? i used Linux=true and false but both times i get the error. Screenshots setup aswell

**Comment by ErrorRExorY** [comment]
Now only getting one screenshot from resource stopper and after that, any action doesnt have a screenshot attached.

**Comment by ErrorRExorY** [comment]
> > Anyone know why? I need those screenshots ^^
> 
> > 
> 
> > I tried it like this:
> 
> > 
> 
> > ```
> 
> >     local OWNER = NetworkGetFirstEntityOwner(ENTITY)
> 
> >     local TYPE, POPULATION, MODEL, HWID = GetEntityType(ENTITY), GetEntityPopulationType(ENTITY),
> 
> >         GetEntityModel(ENTITY), GetPlayerToken(OWNER, 0)
> 
> >         
> 
> >         
> 
> >         And like suggested above
> 
> >         
> 
> >         but i always get
> 
> >         Error: function FIREAC_ACTION (FIREAC.ScreenShot.Log is nil)
> 
> > ```
> 
> > 
> 
> > License: YOUR SERVER NAME
> 
> > 
> 
> > Port is set
> 
> 
> 
> 
> 
> 
> 
> Did you make sure you downloaded the dependencies for screenshotting?
> 
> 

Yeah, i got it working already sorry. ScreenShot.Log isn't set at all for all other. Try with either replacing it with FIREAC.Webhooks.ScreenShot to make it work or create a FIREAC.ScreenShot.Log = "";
Entry in the config
