### ISSUE TITLE
GetPlayerToken

### ISSUE THREAD

**Issue by dambro1990** [AmirrezaJaberi/FIREAC#91]
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[       script:FIREAC] SCRIPT ERROR: Execution of native 0000000054c06897 in script host failed: Argument at index 0 was null.
[       script:FIREAC] > GetPlayerToken (![errore_fireac](https://github.com/AmirrezaJaberi/FIREAC/assets/101954137/fa4cd489-1156-457e-91ab-44f019aaa9b2).lua:6)
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:1293)

**Comment by JustAuramo** [comment]
same here, and some other 
![20240120231528_1](https://github.com/AmirrezaJaberi/FIREAC/assets/108193124/b323ff9d-1b34-46ad-ab0b-c091897558c3)
problems. but how ever, admin menu
![Näyttökuva 2024-01-20 232440](https://github.com/AmirrezaJaberi/FIREAC/assets/108193124/1dae3ce8-fce2-46f5-82a8-500f8d9fe075)
 looks good.
![20240120231934_1](https://github.com/AmirrezaJaberi/FIREAC/assets/108193124/bd75a492-ec70-4ef1-a2a4-05f45ef95aca)

**Comment by IsolatedRP** [comment]
How we fixed the issue, was replacing replace the line 956 to 957 in fire.server.lua with the following information
local TYPE       = GetEntityType(ENTITY)
local OWNER      = NetworkGetFirstEntityOwner(ENTITY)
local POPULATION = GetEntityPopulationType(ENTITY)
local MODEL      = GetEntityModel(ENTITY)
local HWID       = GetPlayerToken(OWNER, 0)

that should fix the playertoken issue. 
my next issue is "fireac_meesage" which would you would need to change to  "fireac_message" as that is for function name.

**Comment by ByQuadiix** [comment]
Replace line 1292-1293 with this:
local TYPE = GetEntityType(ENTITY)
	local OWNER = NetworkGetFirstEntityOwner(ENTITY)
	local POPULATION = GetEntityPopulationType(ENTITY)
	local MODEL = GetEntityModel(ENTITY)
	local HWID = GetPlayerToken(OWNER, 0)

         GetEntityPopulationType(ENTITY)
	 GetEntityModel(ENTITY) 
	 GetPlayerToken(OWNER, 0
