### ISSUE TITLE
All Menu Buttons dont work

### ISSUE THREAD

**Issue by ByQuadiix** [AmirrezaJaberi/FIREAC#92]
![FiveM® by Cfx re - Skyon-V 2 0 _  ALPHA VERSION  26 01 2024 13_38_00](https://github.com/AmirrezaJaberi/FIREAC/assets/157807042/fedeb16f-8e45-4bf8-9fc2-c1922c72ee99)

I looked in the HTML and didnt notice any unusual things.
Here is my HTML
[index.html.txt](https://github.com/AmirrezaJaberi/FIREAC/files/14064925/index.html.txt)

**Comment by r0uzy** [comment]
same

**Comment by Hexney272** [comment]
same

**Comment by minipunch** [comment]
can confirm

**Comment by yamaon** [comment]
Any Solution?
