### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by BallisticOK** [AmirrezaJaberi/FIREAC#98]
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:1293)
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[       script:FIREAC] SCRIPT ERROR: Execution of native 0000000054c06897 in script host failed: Argument at index 0 was null.

**Comment by minipunch** [comment]
Yeah, can confirm. Getting this issue as well.

`GetPlayerToken(OWNER, 0)` is not working cause I guess the `OWNER` is null most likely within the `entityCreated` handler

**Comment by minipunch** [comment]
this is the commit that broke it: https://github.com/AmirrezaJaberi/FIREAC/commit/90ed8c668c91a1093aa83fd55db08f9473f8a61f
